Repository xarray-contrib/datatree, pull requests merged in 2021-12, with the labels that each got.

#50 Add assert_equal functions
  conftest.py
  datatree/datatree.py
  datatree/formatting.py
  datatree/mapping.py
  datatree/testing.py
  datatree/tests/test_formatting.py
  datatree/tests/test_mapping.py
Labels: enhancement, testing

#52 fix bug where zarr's consolidated metadata is created after writing each group
  datatree/datatree.py
  datatree/io.py
  datatree/tests/test_datatree.py
Labels: bug

#53 Use new assert_equal functions in tests
  datatree/tests/test_dataset_api.py
  datatree/tests/test_datatree.py
  datatree/tests/test_mapping.py
Labels: testing
