Repository xarray-contrib/datatree, pull requests merged in 2022-12, with the labels that each got.

#159 actually allow `DataTree` objects as values in `from_dict`
  datatree/datatree.py
  datatree/tests/test_datatree.py
  docs/source/whats-new.rst
Labels: bug

#167 Update README.md
  README.md
Labels: documentation

#169 Improved exception types
  datatree/__init__.py
  datatree/tests/test_datatree.py
  datatree/tests/test_treenode.py
  datatree/treenode.py
  docs/source/api.rst
  docs/source/whats-new.rst
Labels: enhancement

#173 Use xarray docs theme instead of pangeo
  ci/doc.yml
  docs/Makefile
  docs/source/conf.py
  docs/source/whats-new.rst
Labels: documentation

#170 Descendants property
  datatree/tests/test_treenode.py
  datatree/treenode.py
  docs/source/api.rst
  docs/source/whats-new.rst
Labels: enhancement

#172 Name permanence via shallow copy
  datatree/datatree.py
  datatree/tests/test_datatree.py
  datatree/tests/test_mapping.py
  docs/source/whats-new.rst
Labels: enhancement

#174 Terminology
  docs/source/index.rst
  docs/source/terminology.rst
  docs/source/whats-new.rst
Labels: documentation

#175 Added drop_nodes method
  datatree/datatree.py
  datatree/tests/test_datatree.py
  docs/source/api.rst
  docs/source/whats-new.rst
Labels: enhancement
