Repository xarray-contrib/datatree, pull requests merged in 2022-06, with the labels that each got.

#109 Enable tree-style HTML representation
  datatree/formatting_html.py
  datatree/tests/test_formatting_html.py
  docs/source/whats-new.rst
Labels: html repr

#115 Allow assigning Coercible values + NamedNode internal class
  datatree/datatree.py
  datatree/tests/test_datatree.py
  datatree/tests/test_treenode.py
  datatree/treenode.py
  docs/source/whats-new.rst
Labels: bug

#103 Data structures docs
  datatree/datatree.py
  docs/source/data-structures.rst
  docs/source/index.rst
  docs/source/whats-new.rst
Labels: documentation
